version: "3"

services:
  es:
    image: elasticsearch:8.10.2
    ports:
      - "9200:9200"
    expose:
      - 9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - ./esdata:/usr/share/elasticsearch/data
    # networks:
    #   - es
  kibana:
    container_name: kibana
    depends_on:
      - es
    image: kibana:8.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
#     networks:
#       - es
#
# networks:
#   es:
