version: "3"

services:
  es:
    container_name: elasticsearch
    build: 
      context: .
      dockerfile: Dockerfile.es
    ports:
      - "9200:9200"
    expose:
      - 9300
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - es

  kibana:
    container_name: kibana
    depends_on:
      - es
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - es

networks:
  es:
